name: Sync Fork with Upstream
on:
  push:
    branches:
      - main
jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ref: main

      - name: Set up Git
        run: |
          git config --global user.email 83216092+MarkusSchilling@users.noreply.github.com
          git config --global user.name MarkusSchilling

      - name: Fetch upstream changes
        run: git fetch upstream

      - name: Merge upstream changes
        run: git merge upstream/main --no-edit

      - name: Push changes to fork
        run: git push origin main
