name: Sync Fork with Upstream
on:
  push:
    branches:
      - main
jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ref: main

      - name: Set up Git
        run: |
          git config --global user.email 83216092+MarkusSchilling@users.noreply.github.com
          git config --global user.name MarkusSchilling

      - name: Add upstream remote
        run: git remote add upstream https://github.com/scientific-ontology-network/ontology-development-guide
      
      - name: Pull upstream
        run: git pull --unshallow

      - name: Check if workflow file is modified
        id: check_workflow_changes
        run: |
          git diff --name-only HEAD^ HEAD | grep -qE '\.github/workflows/'

      - name: Fetch upstream changes
        if: steps.check_workflow_changes.outputs.return-value == '0'
        run: git fetch upstream

      - name: Merge upstream changes
        if: steps.check_workflow_changes.outputs.return-value == '0'
        run: git merge upstream/main --no-edit --allow-unrelated-histories || echo "Merge conflict occurred"

      - name: Check for merge conflicts
        run: |
          if git diff --quiet; then
            echo "No merge conflicts found. Proceeding with push."
          else
            echo "Merge conflicts found. Please resolve conflicts manually and commit changes."
            exit 1
          fi

      - name: Push changes to fork
        if: steps.check_workflow_changes.outputs.return-value == '0'
        run: git push origin main
